#+TITLE: Начало работы с паттернами
#+AUTHOR: Bjornmossa
#+LANGUAGE: ru
#+HTML_HEAD_EXTRA: <meta charset="utf-8">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./assets/style.css" />

* Пара слов о переменных.

Язык SuperCollider взял многое от функциональных языков, в том числе
очень строгое отношение к области видимости переменных. В большинстве
случаев мы будем избегать работы с переменными, но столкнуться с ними
прийдётся. Итак, переменная это поименованная область памяти
компьютера, в которую мы записали некоторое значение.[fn:2] Можно
представить это как ячейку в камере хранения. Мы знаем название этой
ячейки, можем что-то в неё положить или забрать. Чтобы положить
что-либо в нашу ячейку обычно используется оператор присваивания, обычно
это знак равенства *=*. Мы можем хранить в этой ячейке только что-то
одно, поэтому когда мы кладем новую вещь в ячейку старая исчезает.
Для создания переменной используется ключевое слово ~var~. Созданная
таким образом переменная называется локальной[fn:1] и существует
только внутри блоков кода, т.е между конструкциями из обычных ~()~
или фигурных ~{}~ скобок. 

#+BEGIN_SRC sclang
(
var my_variable = 1;
my_variable.postln; // 1
)

my_variable.postln; // ошибка. За скобками переменной my_variable не существует.
#+END_SRC

В тех случаях, когда нам нужно будет объявить глобальную переменную[fn:3], т.е переменную,
к которой можно обратиться в любой части кода, мы будем использовать имена, начинающиеся со знака
тильда =~=. Такие переменные можно объявлять где угодно.

#+BEGIN_SRC sclang
  (
  ~my_global_variable = 1;
  )

  ~my_second_global_variable = 2;

  ~my_global_variable.postln; // 1
  ~my_global_variable2.postln; // 2
#+END_SRC

* Паттерны, потоки, события.

Для того, чтобы начать работать с мелодиями и гармониями
в SuperCollider необходимо ясное понимание того, что такое
паттерны (Pattern), потоки (Stream) и события (Events).
Начнём с потоков.

** Потоки (Streams)

Для того, чтобы создать музыкальную композицию нам понадобится
инструмент, который позволит воспроизводить звуковые события
одно за другим. Представьте, что вы играете на фортепиано.
Чтобы звучала мелодия вам нужно нажимать клавишу за клавишей.
Это и есть своеобразный поток. В языке SuperCollider
поток --- это объект, который содержит последовательность
значений, которые можно получить с помощью сообщения ~.next~ .

Cообщения --- одна из особенностей языка. Чтобы отправить
сообщение нужно написать его через точку после целевого
объекта. Объект, которому посылается сообщение называется
получателем (receiver). Во многих других языках это называется
вызов метода. Выше мы видели, как отправить сообщение .postln любой
переменной. Это сообщение выведет на экран значение этой переменной.

Кроме того поток может быть остановлен, поставлен на паузу и позже
запущен с помощью сообщений ~.stop~ ~.pause~ и ~.resume~ соответственно.
Поток довольно абстрактное понятие. Не переживайте, если что-то из
прочитаного осталось непонятным. Мы не будем работать с ними напрямую, но
понимание того, что это такое сильно облегчит нам работу с паттернами.

** События (Events)

Событие --- это действие, которое должно быть вызвано в ответ
на сообщение =.play= . Событие является парой ключ-значение.
Работая с паттернами мы будем часто встречать их. Вот список
некоторых событий, которые мы будем использовать:

- ~\note~ --- нота
- ~\freq~ --- частота (в Герцах)
- ~\octave~ --- октава
- ~\amp~ --- амплитуда (громкость)
- ~\dur~ --- длительность

Вот как выглядят события в паттерне.

#+BEGIN_SRC sclang 
Pbind(
  \dur, 1/4,
  \octave, 4,
  \note, 0,
  \amp, 0.5
);
#+END_SRC

В приведенном примере ключ события это ~\dur~, а значение --- ~1/4~.

Но что же такое ~Pbind~? Сейчас мы заглянем чуток дальше.
~Pbind~ это и есть паттерн. Название каждого паттерна начинается
с заглавной P. Паттернов довольно много и все они выполняют свою
функцию. Паттерн ~Pbind~ комбирирует события в один поток.
Отправив сообщение ~.play~ паттерну Pbind, мы получим поток, который
воспроизведет ноту До (~\note, 0~) четвертой октавы (~\octave, 4~)
с громкостью в половину обычного (~\amp, 0.5~) в течении
1/4 секунды (~/dur, 1/4~).

** Паттерны

Теперь, имея базовое представление о паттернах, можно попробовать воспроизвести простую мелодию.
Для этого выполните следующий код:

#+BEGIN_SRC sclang
~stream = Pbind(
  \dur, 1/4,
  \octave, 4,
  \note, Pseq([0, 2, 4], inf),
  \amp, 0.5
).play;
#+END_SRC

Теперь мелодия играет постоянно. Сначала остановим её, а потом подробно разберём эту часть.
В примере выше мы сохранили в глобальной переменной =~stream= результат отправки сообщения ~.play~
паттерну Pbind. Таким образом мы сохранили поток. Мы уже знаем о том как остановить его.
Нужно отправить потоку сообщение ~.stop~ .

#+BEGIN_SRC sclang
~stream.stop;
#+END_SRC

Что же позволило паттерну играть мелодию? Наверняка вы обратили внимание на конструкцию ~\note, Pseq([0, 2, 4], inf)~ .
Это обычное событие, только в качестве ключа у этого события не простое значение, а паттерн Pseq.


* Pseq

Pseq --- это паттерн, возвращающий несколько значений одно за
другим заданное количество раз. Паттерн принимает в качестве
аргументов массива[fn:4] значений (в квадратных скобках [])
и количество повторений. В примере выше в качестве количества
повторений мы использовали ключевое слово ~inf~ --- это обозначение
бесконечности в Supercollider. Стоит заметить, что если внутри
паттерна есть несколько паттернов Pseq, то поток завершится
тогда, когда завершится самый короткий из паттернов.
Взгляните на пример:

#+BEGIN_SRC sclang
Pbind(
\dur, Pseq([1/4, 1/2], inf),
\note, Pseq([0, 2, 4], 2)
);
#+END_SRC

Этот паттерн завершится после двух воспроизведений, так как
это количество повторов в самом коротком паттерне. В качестве
значений Pseq может принимать что угодно, в том числе другие
паттерны. Это очень удобно в том случае, если вы хотите запустить
два паттерна один за другим. Но что делать, если вым нужно
воспроизвести аккорд? Неужели придётся писать по паттерну для
каждой ступени аккорда? К счастью нет. Дело в том, что если
в качестве значения события будет не число, а массив, то
интерпретатор SuperCollider автоматически создаст количество
событий, равное длинне массива. Тут стоит сказать, что в
программировании счёт начинается не с единицы, а с нуля, поэтому
для того, чтобы воспроизвести аккорд до--мажор, для которого
нужны ноты до ми и соль нам понадобится массив из чисел
0, 2 и 4, а не 1, 3 и 5.

#+BEGIN_SRC sclang
Pbind(
\dur, 1,
\note, [0, 2, 4]
);
#+END_SRC

Вот так выглядит паттерн, который воспроизведёт аккорд до--мажор
в течении одной секунды. Теперь, зная о паттерне Pseq и о
том, как можно воспроизвести несколько событий одновременно, мы
можем сыграть аккордовую последовательность. Для этого нужно
передать первым аргументом паттерна Pseq массив, состоящий из
массивов, например:

#+BEGIN_SRC sclang
Pbind(
\note, Pseq(
    [
      [0, 2, 4],
      [1, 3, 5],
      [2, 4, 6]
    ],
    2
  ),
\dur, 1
);
#+END_SRC

Чтож, взглянув на эту конструкцию может показаться, что партитуры
Ксенакиса[fn:5] выглядят проще и понятнее. Конечно, это преувеличение,
но всё же намного лучше иметь возможность работать с чем-то
более приближенным к музыкальной теории, чтобы не утруждать
свом мозг постоянными трансформациями нот в числа и обратно.
Благодаря тому, что SuperCollider это свободное и открытое
программное обеспечение[fn:6] , каждый пользователь может внести
свою лепту в развитие проекта, изменить код или написать
дополнение. Поэтому для работы с нотами и аккордами мы будем
использовать библиотеку ChordSymbol[fn:7], которая позволяет
использовать буквенные наименования нот и аккордов.

* Библиотека ChordSymbol, ноты и аккорды



* Footnotes

[fn:7] https://github.com/triss/ChordSymbol

[fn:6] https://ru.wikipedia.org/wiki/%D0%A1%D0%B2%D0%BE%D0%B1%D0%BE%D0%B4%D0%BD%D0%BE%D0%B5_%D0%B8_%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%B5_%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5

[fn:5] https://ru.wikipedia.org/wiki/%D0%9A%D1%81%D0%B5%D0%BD%D0%B0%D0%BA%D0%B8%D1%81,_%D0%AF%D0%BD%D0%B8%D1%81

[fn:4] https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%81%D1%81%D0%B8%D0%B2_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

[fn:3] https://ru.wikipedia.org/wiki/%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F

[fn:1] https://ru.wikipedia.org/wiki/%D0%9B%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F

[fn:2] https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

